name: Droplet Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SSH to Droplet
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DIR }}
          docker compose down
          git pull
          docker compose up -d

    - name: Wait for deployment
      run: sleep 30

    # Make script executable and run checks
    - name: Check page rendering
      uses: actions/checkout@v4
    - run: |
        chmod +x ./check-pages.sh
        ./check-pages.sh "${{ vars.RELAY_URL }}"
